version: "3.8"
services: 
    api:
        build: .
        depends_on:
          - db
        ports:
          - 8000:8000
        volumes: 
          - ./:/usr/src/app:ro
        command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
        environment:
          - DATABASE_HOSTNAME=db
          - DATABASE_PORT=5432
          - DATABASE_PASSWORD=postgres
          - DATABASE_NAME=fastapi
          - DATABASE_USERNAME=postgres
          - SECRET_KEY=somesecretetkeyword
          - ALGORITHM=HS256
          - ACCESS_TOKEN_EXPIRE_IN_MINUTES=120
    
    db:
      image: postgres:14.1-alpine
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=fastapi
      ports:
       - '5433:5433'
      volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local


     